### ISSUE TITLE
Add country specific number formats in phoneNumbers/numberInClipboard.py and phoneNumbers/numberInFile.py

### ISSUE THREAD

**Issue by emilmerle** [emilmerle/FindingThingsWithPython#1]
Please add regular expressions that match the number format in a specific country or state and add that to the existing dictionary.
Number format for germany is already given.

- [ ] Add regular expression
- [ ] Add regex to dictionary

**Comment by rexdivakar** [comment]
Please assign it to me i will work on this @emilmerle
