### ISSUE TITLE
Add a Readme in your first/native language

### ISSUE THREAD

**Issue by emilmerle** [emilmerle/FindingThingsWithPython#4]
Please add the Readme in your first/ native language or in languages you know. 
Keep the format of the english version (README.md) and provide links to the other languages. 
Also add the link to your new version in the english version.

**Comment by rexdivakar** [comment]
How many languages are u expecting to add ?

**Comment by emilmerle** [comment]
As many as possible. I wont close this issue so everyone can add their language. 
If you want to add yours you can open a pull request for it.

**Comment by iriyagupta** [comment]
@emilmerle Created a pull request corresponding to README.md for hi language (Hindi).

**Comment by KickItLikeShika** [comment]
I will work on this (Arabic). Just i'll wait till hacktoberfest starts

**Comment by KickItLikeShika** [comment]
@emilmerle I have just made a pull request for the Arabic reamde file. Please review my pull request
